config/routes.rb
Rails.application.routes.draw do
  root "home#index" 
  
    devise_for :users
	get "users/:id", to: "home#index"
	get "/", to: "home#index" 
	get "users/:id/club", to: "clubs#club", as: "club"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/[users]/confirmations_controller.rb
# frozen_string_literal: true

class [users]::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/[users]/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class [users]::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/[users]/passwords_controller.rb
# frozen_string_literal: true

class [users]::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/[users]/registrations_controller.rb
# frozen_string_literal: true

class [users]::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/[users]/sessions_controller.rb
# frozen_string_literal: true

class [users]::SessionsController < Devise::SessionsController
  before_action :authenticate_user? 
  

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/[users]/unlocks_controller.rb
# frozen_string_literal: true

class [users]::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception


protected

def configure_permitted_parameters
	added_attrs = [:firstname, :lastname, :email, :password, :password_confirmation, :remember_me]
	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:firstname, :lastname)}


end 

private

def after_sign_out_path_for(resource_or_scope)
	root_path 
end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
	
	 before_action :authenticate_user!
  def club
  	@users = User.all 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clubs/club.html.erb
<h1>Emails du club</h1>

<% @users.each do |club| %>
<h2><%= club.email %></h2>
<% end %>

app/views/home/index.html.erb
<h1>PAGE ACCUEIL !</h1>
<p></p>

app/views/layouts/_navbar.html.erb
<div id="wrapper" class="active">  
    <!-- Sidebar -->
            <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul id="sidebar_menu" class="sidebar-nav">
           <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
        </ul>
        <ul class="sidebar-nav" id="sidebar">
          <li><a><span class="sub_icon glyphicon glyphicon-link"></span><%= link_to "Accueil", root_path %></a></li>
          <% if user_signed_in? %>
           <ul class="sidebar-nav" id="sidebar">
                <li><a><span class="sub_icon glyphicon glyphicon-link"></span><%= link_to "Club", club_path(:id) %></a></li>
                <li><a><span class="sub_icon glyphicon glyphicon-link"></span><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></a></li>
           </ul>
           <% else %>
          <li><a><span class="sub_icon glyphicon glyphicon-link"></span><%= link_to "S'enregistrer", new_user_registration_path %></a></li>
          <li><a><span class="sub_icon glyphicon glyphicon-link"></span><%= link_to "Se connecter", new_user_session_path %></a></li>
        </ul>
        <% end %>
     </div>     
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= render "layouts/navbar" %>
    <title>PAGE PRIVEE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  </head>

  <body>
    <div style='text-align: center'>


    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>